### ISSUE TITLE
rolling replace of k8s nodes causes "No Cluster Leader"

### ISSUE THREAD

**Issue by nmnellis** [kelseyhightower/consul-on-kubernetes#13]
Sometimes I have to use Kops to do a rolling replace of the current nodes and this requires moving the consul cluster master nodes to new k8s nodes. Every time this is performed I have to manually reconnect the consul master nodes. Does anyone know of a way to have the consul nodes reconnect after they move k8s nodes? This also happens with k8s node taints.

**Comment by santinoncs** [comment]
You need to keep the consensus. If you got 3 consul nodes, you need at least 2 working.
Ensure that you move the consul nodes never breaking this.

**Comment by nmnellis** [comment]
@santinoncs i dont believe that is the answer, since all k8s nodes will be replaced every consul server pod will be shutdown and moved which means the preStop action is getting called which calls `consul leave`. When the new instance of the consul server is brought back up there is no mechanism to have it automatically rejoin the cluster.

**Comment by santinoncs** [comment]
Yes, you need a rejoin mechanism. This is the one I am using

```containers:
      - name: "{{ template "name" . }}"
        image: "{{.Values.Image}}:{{.Values.ImageTag}}"
        imagePullPolicy: "{{.Values.ImagePullPolicy}}"
        args:
        - "agent"
        - "-server"
        - "-client"
        - "0.0.0.0"
        - "-recursor"
        - "8.8.8.8"
        - "-bootstrap-expect"
        - "3"
        - "-retry-join"
        - "traefik-consul"
        - "-ui"```


This is an extract of my statefulset manifest

**Comment by nmnellis** [comment]
@santinoncs thanks for your help, i was able to remove the need for the k8s job by placing the retry-join in the statefulset like below
```yaml
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=3"
            - "-client=0.0.0.0"
            - "-config-file=/etc/consul/consul.json"
            - "-datacenter=dc1"
            - "-data-dir=/var/lib/consul"
            - "-domain=cluster.local"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
            - "-retry-join=consul.$(NAMESPACE).svc.cluster.local"
```

**Comment by SukantGujar** [comment]
@nmnellis Could you share your yamls please? We are facing similar issues when GKE autoscales the cluster. Thanks!

**Comment by nmnellis** [comment]
@SukantGujar 
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 5
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - consul
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        node.type: generic
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "consul:0.8.1"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=5"
            - "-client=0.0.0.0"
            - "-config-file=/etc/consul/server.json"
            - "-datacenter=dc1"
            - "-data-dir=/var/lib/consul"
            - "-domain=cluster.local"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
            - "-retry-join=consul.$(NAMESPACE).svc.cluster.local"
          volumeMounts:
            - name: data
              mountPath: /var/lib/consul
            - name: config
              mountPath: /etc/consul
            - name: tls
              mountPath: /etc/tls
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      volumes:
        - name: config
          configMap:
            name: consul
        - name: tls
          secret:
            secretName: consul  
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: default
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
