### ISSUE TITLE
PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by danil-demidov** [kelseyhightower/consul-on-kubernetes#20]
Hello.
I has been create kubernetes cluster ( [https://www.linuxtechi.com/install-kubernetes-1-7-centos7-rhel7/#comment-1221](url) ).
I has been installed kubernetes dashboard.
Now, I trying to install consul, but I got error: _PersistentVolumeClaim is not bound: "data-consul-0" (repeated 4 times)_
I has been create "Persistent Volumes" (_isshues blachniet_) - it's didn't help.
What could be else the problem?

**Comment by Lax77** [comment]
Am also seeing similar issue. Does it mean the volumeClaimTemplates config expecting the volume created explicitly prior to deploying the statefulset?

**Comment by tankchintan** [comment]
@danil-demidov @Lax77 Someone created a PR for resolving this. See [here](https://github.com/kelseyhightower/consul-on-kubernetes/pull/21).

**Comment by elordahl** [comment]
There are a number of ways to resolve this.  If you're using AWS, you could create an `AWSElasticBlockStore` **storageClass** and assign assign it to the `volumeClaimTemplates` `spec` as `storageClassName` (see below):

aws-example.yml
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: consul-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

statefulsets/consul.yml
```yaml
  volumeClaimTemplates:
    - metadata:
        name: data
       spec:
         storageClassName: consul-storage
     ...
```
