### ISSUE TITLE
AntiAffinity prevents containers from starting on single node

### ISSUE THREAD

**Issue by Seth-Miller** [kelseyhightower/consul-on-kubernetes#29]
I am using minikube with only a single node. Because the statefulset has an anti-affinity rule, only the first container will start. Simply changing this from anti-affinity to affinity fixes the problem and allows all three containers to start.

```
      affinity:
#        podAntiAffinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - consul
              topologyKey: kubernetes.io/hostname
```
