### ISSUE TITLE
No cluster leader

### ISSUE THREAD

**Issue by danielckv** [kelseyhightower/consul-on-kubernetes#3]
When I'm calling to the HTTP service from my app it's sending me an error with this message: No cluster leader

**Comment by kelseyhightower** [comment]
I've updated the tutorial and it seems to be working well for me. Please reopen if things don't work in the latest tutorial.

**Comment by suninuni** [comment]
```
containers:
        - name: consul
          image: docker.xxxxx.com/service/consul-server:latest
          command:
            - "/bin/consul"
            - "join"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-rpc-addr=consul-0.consul.$(NAMESPACE).svc.cluster.local:8400"
            - consul-0.consul.$(NAMESPACE).svc.cluster.local
            - consul-1.consul.$(NAMESPACE).svc.cluster.local
            - consul-2.consul.$(NAMESPACE).svc.cluster.local
```

I encountered the same problem, but I modified the consul-join job as this, it works well.
